### ISSUE TITLE
search criteria on _id

### ISSUE THREAD

**Issue by peterkoelgaard** [le-yams/netbeans-mongodb#23] opened 2015-05-28 08:01 UTC
How do I get a document from a collection by passing an _id as criteria?
I tried different variations of the following syntax:
"_id":"5523bc30b0f9671016e9d152"
but then I get an "invalid criteria json" ..is there a manual or documentation somewhere for future reference?

**Comment by le-yams** [comment] 2015-05-28 09:53
Hi Peter,

The criteria must be a valid json document so the first thing to do is add the document braces `{ ... }`.
Also, the "_id" field is not a string property but a mongo ObjectId.
You can't use the mongo syntax ObjectId("...") because of the json validity constraint but you can use the json representation which is:
```json
{
  "_id":{
    "$oid":"5523bc30b0f9671016e9d152"
  }
}
```

I understand this is not very handy and adding some support for the mongo specific syntax (or maybe disable the json validity constraint) would be a plus. I created the issue #24 to work on that, don't hesitate to comment it or share any thought/idea.

For the manual/documentation, there currently isn't that comes with the plugin. I use the mongo java driver (v2.13 for the current plugin version) so anything accepted by it should work except for the json invalid syntax.

Best regards,
Yann

**Comment by peterkoelgaard** [comment] 2015-05-28 10:47
Hi Yann

Thank you for your fast response.
It works like a charm.
I posted my comment thinking others could benefit from your answer as well.
Thanks for helping out :)

Peter Kølgaard.

________________________________
Fra: Yann [notifications@github.com]
Sendt: 28. maj 2015 11:53
Til: le-yams/netbeans-mongodb
Cc: Peter Kølgaard
Emne: Re: [netbeans-mongodb] search criteria on _id (#23)


Hi Peter,

The criteria must be a valid json document so the first thing to do is add the document braces { ... }.
Also, the "_id" field is not a string property but a mongo ObjectId.
You can't use the mongo syntax ObjectId("...") because of the json validity constraint but you can use the json representation which is:

{
  "_id":{
    "$oid":"5523bc30b0f9671016e9d152"
  }
}

I understand this is not very handy and adding some support for the mongo specific syntax (or maybe disable the json validity constraint) would be a plus. I created the issue #24<https://github.com/le-yams/netbeans-mongodb/issues/24> to work on that, don't hesitate to comment it or share any thought/idea.

For the manual/documentation, there currently isn't that comes with the plugin. I use the mongo java driver (v2.13 for the current plugin version) so anything accepted by it should work except for the json invalid syntax.

Best regards,
Yann

**Comment by le-yams** [comment] 2015-05-28 12:32
You're welcome :-)
I close this issue as a duplicate of #24 which focus on the mongo syntax support improvement.

Yann

**Closed by le-yams** 2015-05-28 12:32 UTC
Labels: duplicate
